# TCL File Generated by Component Editor 15.1
# Wed Apr 13 03:31:59 EDT 2016
# DO NOT MODIFY


# 
# DDR_TEST "DDR_TEST" v1.0
#  2016.04.13.03:31:59
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module DDR_TEST
# 
set_module_property DESCRIPTION ""
set_module_property NAME DDR_TEST
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME DDR_TEST
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL SoCKit_DDR3_RTL_Test
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file SoCKit_DDR3_RTL_Test.v VERILOG PATH SoCKit_DDR3_RTL_Test.v TOP_LEVEL_FILE
add_fileset_file Avalon_bus_RW_Test.v VERILOG PATH FPGA_DDR3/Avalon_bus_RW_Test.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock ""
set_interface_property avalon_slave_0 associatedReset ""
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 AUD_ADCDAT beginbursttransfer Input 1
add_interface_port avalon_slave_0 AUD_ADCLRCK export Bidir 1
add_interface_port avalon_slave_0 AUD_BCLK export Bidir 1
add_interface_port avalon_slave_0 AUD_DACDAT writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 AUD_DACLRCK export Bidir 1
add_interface_port avalon_slave_0 AUD_I2C_SCLK writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 AUD_I2C_SDAT export Bidir 1
add_interface_port avalon_slave_0 AUD_MUTE writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 AUD_XCK writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 DDR3_A readdata Output 15
add_interface_port avalon_slave_0 DDR3_BA readdata Output 3
add_interface_port avalon_slave_0 DDR3_CAS_n writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 DDR3_CKE writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 DDR3_CK_n writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 DDR3_CK_p writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 DDR3_CS_n writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 DDR3_DM readdata Output 4
add_interface_port avalon_slave_0 DDR3_DQ export Bidir 32
add_interface_port avalon_slave_0 DDR3_DQS_n export Bidir 4
add_interface_port avalon_slave_0 DDR3_DQS_p export Bidir 4
add_interface_port avalon_slave_0 DDR3_ODT writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 DDR3_RAS_n writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 DDR3_RESET_n writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 DDR3_RZQ beginbursttransfer Input 1
add_interface_port avalon_slave_0 DDR3_WE_n writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 FAN_CTRL writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 HSMC_CLKIN_n export Bidir 2
add_interface_port avalon_slave_0 HSMC_CLKIN_p export Bidir 2
add_interface_port avalon_slave_0 HSMC_CLKOUT_n export Bidir 2
add_interface_port avalon_slave_0 HSMC_CLKOUT_p export Bidir 2
add_interface_port avalon_slave_0 HSMC_CLK_IN0 export Bidir 1
add_interface_port avalon_slave_0 HSMC_CLK_OUT0 export Bidir 1
add_interface_port avalon_slave_0 HSMC_D export Bidir 4
add_interface_port avalon_slave_0 HSMC_RX_n export Bidir 17
add_interface_port avalon_slave_0 HSMC_RX_p export Bidir 17
add_interface_port avalon_slave_0 HSMC_SCL writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 HSMC_SDA export Bidir 1
add_interface_port avalon_slave_0 HSMC_TX_n export Bidir 17
add_interface_port avalon_slave_0 HSMC_TX_p export Bidir 17
add_interface_port avalon_slave_0 IRDA_RXD beginbursttransfer Input 1
add_interface_port avalon_slave_0 KEY writebyteenable_n Input 4
add_interface_port avalon_slave_0 LED readdata Output 4
add_interface_port avalon_slave_0 OSC_50_B3B beginbursttransfer Input 1
add_interface_port avalon_slave_0 OSC_50_B4A beginbursttransfer Input 1
add_interface_port avalon_slave_0 OSC_50_B5B beginbursttransfer Input 1
add_interface_port avalon_slave_0 OSC_50_B8A beginbursttransfer Input 1
add_interface_port avalon_slave_0 PCIE_PERST_n beginbursttransfer Input 1
add_interface_port avalon_slave_0 PCIE_WAKE_n beginbursttransfer Input 1
add_interface_port avalon_slave_0 SI5338_SCL export Bidir 1
add_interface_port avalon_slave_0 SI5338_SDA export Bidir 1
add_interface_port avalon_slave_0 SW writebyteenable_n Input 4
add_interface_port avalon_slave_0 TEMP_CS_n writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 TEMP_DIN writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 TEMP_DOUT beginbursttransfer Input 1
add_interface_port avalon_slave_0 TEMP_SCLK writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 USB_B2_CLK beginbursttransfer Input 1
add_interface_port avalon_slave_0 USB_B2_DATA export Bidir 8
add_interface_port avalon_slave_0 USB_EMPTY writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 USB_FULL writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 USB_OE_n beginbursttransfer Input 1
add_interface_port avalon_slave_0 USB_RD_n beginbursttransfer Input 1
add_interface_port avalon_slave_0 USB_RESET_n beginbursttransfer Input 1
add_interface_port avalon_slave_0 USB_SCL export Bidir 1
add_interface_port avalon_slave_0 USB_SDA export Bidir 1
add_interface_port avalon_slave_0 USB_WR_n beginbursttransfer Input 1
add_interface_port avalon_slave_0 VGA_B readdata Output 8
add_interface_port avalon_slave_0 VGA_BLANK_n writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 VGA_CLK writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 VGA_G readdata Output 8
add_interface_port avalon_slave_0 VGA_HS writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 VGA_R readdata Output 8
add_interface_port avalon_slave_0 VGA_SYNC_n writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 VGA_VS writeresponsevalid_n Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset RESET_n reset_n Input 1

